// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhpjvfsotwkfvaeqikco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVocGp2ZnNvdHdrZnZhZXFpa2NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3OTkwMjcsImV4cCI6MjA1NjM3NTAyN30.JHlrv_AtwMcTZIGt-Y03XRvYp-7IwaLuc4YuczOWATU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);